### PR TITLE
Related outfits card carousel with API data

### PR DESCRIPTION
**Pull request by danitian**
@sheebanair Please take a look when you have a moment! I've manually tested my component to make sure it works.

Specs 1.4.1 and 1.4.2 sections complete:
- set up all requests and data flow so that related outfits carousel now renders data from the API correctly
- removed example data code
- added sale price render if item is on sale
- need Sheeba's star ratings component for the star ratings

Tests:
- added a sample test to make sure related.test.js is hooked up to related.jsx for my related products component

Misc:
- added a babel.config.js file to make sure that jest can handle jsx code. It kept on running into error on importing modules before

### CODE REVIEW

**Comment by danitian** [comment]
Looks like my sample test is failing while it passes locally. I'll check on it some time later

**Comment by danitian** [comment]
Oh I think I know why the test failed. styled-components is not yet in the package.json and I didn't push up my own updated package.json. Will do next time

**Review by sheebanair — COMMENTED** [review]
Hi @danitian, this looks good. Just wanted to check with you if you are planning to import the config token directly to client side or are you later going to route it through the server? I am not 100% sure but I think it's more likely to get compromised if you do it this way. 

Also I see that your mock test are setup as expected but they are failing currently in circleci. Can we fix this before the merge?

**Comment by danitian** [comment]
Tests have passed. Your comment about the config is a good call out. I've been staying away from the server index.js out of fear of messing it up since it's shared, but I'll need to do a refactor at some point to put all my actual axios requests on the server side like you said...

**Comment by danitian** [comment]
@sheebanair I've refactored all my api requests to the server side as well!

**Review by sheebanair — APPROVED** [review]
Looks good! I think you can merge it now @danitian!

**Pull request merged**
